name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target fork
        uses: actions/checkout@v4

      - name: Sync upstream changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo sync ${{ github.repository }} --branch master
